version: '3'

services:
  # 仅前端应用
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartclass-manage-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      # 线上后端API地址
      - API_URL=http://backend.smartclass.ubanillx.cn:8081
    volumes:
      # 可选：将nginx配置挂载出来，便于动态修改
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 